server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taco_cloud?serverTimezone=Asia/Shanghai
    username: root
    password: ufo950327
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true